# -*- coding: utf-8 -*-
"""Clean_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bFvhAG1b73ANgjbaRQC-MjwS5YD9T6sE
"""

import pandas as pd

# Read the dataset from the specified path
df = pd.read_csv("/content/Raw_Frality_Score_Data.csv")

# Strip any leading or trailing whitespaces from column names
df.columns = df.columns.str.strip()

# Check for and handle null values
df = df.dropna()

# Convert Frailty column to dummy variables (0 for 'N', 1 for 'Y')
df['Frailty'] = pd.get_dummies(df['Frailty'], drop_first=True)

df.to_csv('Clean_Frailty_Score.csv', index=False)

# Display the preprocessed dataset
print(df)